### ISSUE TITLE
Release plan for v0.3.0

### ISSUE THREAD

**Issue by lidongze0629** [alibaba/GraphScope#128]
Timeline
--------
We plan to release GraphScope 0.3.0 in March 2021.

Major features
---------

**Graph Visualization**

- [x] Support jupyterlab notebook extension (ipygraphin) for graph visualization. (#50)
- [x] Reorganize graphin Jupyter plugin for graphscope. (#208)

**Performance Enhancement**

- [x] Include pre-compiled apps/graphs into docker image (#137)
- [x] improve the response time of each step in Python (#157)

**Kubernetes Releated**

- [x] Deprecate usage of minikube and move to kind (#114, by #129)
- [ ] ~~Proxy all traffic from client in coordinator (#78)~~
- [x] Replace bundled vineyard container with the helm installation. (#89) 
- [x] GraphScope helm support (#161 )

**Integration with Mars**

- [x] Integration with mars (#58 )

~~**Improve the compatibility with NetworkX**~~

**Cloud service integration**

- [x] Provisioning k8s cluster on amazon/aliyun (#57)

**Run GraphScope locally without K8s/Docker**

- [x] Kubernetes is not necessary for GraphScope (#113 )

**Improve graph manipulation APIs**

- [x] a general project operator (#134 )
- [ ] ~~tensor/ndarray attribute (#135 )~~
- [x] optimize the API of create a graph (#142 )
- [x] create new graph by adding new labels of edges and vertices to existing graphs (#138 )

**User-friendly API improvements**
- [x] user-friendly __repr__() for graphscope objects, e.g., for graphs, print out schema in a nice way. (#164 )

**Built-in app extension**
- [x] louvain app(#183)

Known Breaking API Changes
------------------------------

- [x] Deprecate the support for minikube (by #129 )
