### ISSUE TITLE
Python API of GraphScope local storage.

### ISSUE THREAD

**Issue by siyuan0322** [alibaba/GraphScope#298]
- [ ] ~~Finalize the protobuf message format.~~ (duplicated to #321 )
- [ ] ~~The connection and disconnection of session.~~ (duplicated to #320 )
- [ ] ~~Pass the loading data procedure.~~ (duplicated to #297 )
- [ ] ~~The query.~~ (duplicated to #322 )
- [ ] ~~The graph manipulation.~~ (duplicated to #323 )
