### ISSUE TITLE
Release Plan for v0.5.0

### ISSUE THREAD

**Issue by yecol** [alibaba/GraphScope#316]
We are continually polishing GraphScope. 
Hopefully, the next stable version v0.5.0 is going to be release ~~at the end of May~~ before 7 Jun. 
The major features in v0.5.0 include:

- [x] Lazy mode execution support in Python Interface. #303 
- [x] A persistent store for mutable graphs #29 
    - [x] Bulk-load tool to import a property graph from files to the GraphScope instance. #297
    - [x] Helm support to launch GraphScope as service with store. #299 
    - [x] Support of multiple session connections to a store. #320
    - [x] Python API to define schema.  #298 
    - [x] Unified `proto` files for the schema of graph in both store/vineyard. #321
    - [x] Interactive queries on graphs in the store with Gremlin. #322
    - [ ] ~~Real-time interactive mutation for the graphs in the store.  #323~~
- [x] Enhanced NetworkX compatibility #314 
    - [x] Adaption on the engine to support multi-queries on duplications of the whole graph. #317 
    - [x] Based on this adaption, support a set of algorithms like all-pairs shortest paths. #318 
- [x] Provides a Q&A page for beginners. #302 

In addition, we are working on applications from internal business and the next generation for the interactive queries - GAIA, which will be released in the next version.
